const DEFAULT_ERROR_CODE = 500;
const NOT_FOUND_ERROR_CODE = 404;
const VALIDATION_ERROR_CODE = 400;

const DEFAULT_ERROR_MESSAGE = 'DEFAULT ERROR';
const NOT_FOUND_USER_ERROR_MESSAGE = 'USER HAS NOT BEEN FOUND';
const NOT_FOUND_CARD_ERROR_MESSAGE = 'CARD HAS NOT BEEN FOUND';
const VALIDATION_ERROR_MESSAGE = 'INVALID DATA';

module.exports = {
  DEFAULT_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  VALIDATION_ERROR_CODE,
  DEFAULT_ERROR_MESSAGE,
  NOT_FOUND_CARD_ERROR_MESSAGE,
  NOT_FOUND_USER_ERROR_MESSAGE,
  VALIDATION_ERROR_MESSAGE,
};
